<?php
 // module/Album/view/album/album/index.phtml:

 $title = 'Meine Alben';
 $this->headTitle($title);
 echo getenv('APP_ENV');
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <p>
     <a href="<?php echo $this->url('album', array('action'=>'add'));?>">Neues Album hinzuf&uuml;gen</a>
 </p>

 <table class="table">
 <tr>
     <th>Titel</th>
     <th>Artist</th>
     <th>&nbsp;</th>
 </tr>
 <?php foreach ($albums as $album) : ?>
 <tr>
     <td><?php echo $this->escapeHtml($album->getTitle());?></td>
     <td><?php echo $this->escapeHtml($album->getArtist());?></td>
     <td>
         <a href="<?php echo $this->url('album',
             array('action'=>'edit', 'id' => $album->getId()));?>">Bearbeiten</a>
         <a href="<?php echo $this->url('album',
             array('action'=>'delete', 'id' => $album->getId()));?>">L&ouml;schen</a>
     </td>
 </tr>
 <?php endforeach; ?>
 </table>
