<?php
 // module/Album/view/album/album/user.phtml:

 $title = 'Die Benutzer';
 $this->headTitle($fullname);
 echo getenv('APP_ENV');
 ?>
 <h1><?php echo $this->escapeHtml($fullname); ?></h1>
 <p>
     <a href="<?php echo $this->url('user', array('action'=>'add'));?>">Neuen Benutzer hinzuf&uuml;gen</a>
 </p>

 <table class="table">
 <tr>
     <th>Name</th>
     
     <th>&nbsp;</th>
 </tr>
 <?php foreach ($users as $user) : ?>
 <tr>
     <td><?php echo $this->escapeHtml($user->getFullname());?></td>
     <td>
         <a href="<?php echo $this->url('user',
             array('action'=>'edit', 'id' => $user->getId()));?>">Bearbeiten</a>
         <a href="<?php echo $this->url('user',
             array('action'=>'delete', 'id' => $user->getId()));?>">L&0uml;</a>
     </td>
 </tr>
 <?php endforeach; ?>
 </table>
