<?php
 // module/Album/view/album/album/user.phtml:

 
 $title = 'Die Benutzer';
 $this->headTitle($title);
 echo getenv('APP_ENV');
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <p>
     <a href="<?php echo $this->url('user', array('action'=>'add'));?>">Neuen Benutzer hinzuf&uuml;gen</a>
 </p>

 <table class="table">
 <tr>
     <th>Name</th>
     <th>&nbsp;</th>
 </tr>
 <?php foreach ($users as $user) : ?>
 <tr>
     <td><?php echo $this->escapeHtml($user->getfullName());?></td>
     <td>
         <a href="<?php echo $this->url('user',
             array('action'=>'edit', 'id' => $album->getId()));?>">Bearbeiten</a>
         <a href="<?php echo $this->url('user',
             array('action'=>'delete', 'id' => $album->getId()));?>">L&ouml;schen</a>
     </td>
 </tr>
 <?php endforeach; ?>
 </table>
