<?php
 // module/Album/view/share/login/index.phtml:

 $title = 'Share Login';
 $this->headTitle($title);
 ?>
 <h2><?php echo $this->escapeHtml($title); ?></h2>
 <br/><br/>
 <?php


 $form->setAttribute('action', $this->url('login', array('action' => 'index')));
 $form->prepare();

 echo $this->form()->openTag($form);
 ## echo $this->formHidden($form->get('id'));
 echo $this->formRow($form->get('username'));
 echo $this->formRow($form->get('password'));
 echo $this->formSubmit($form->get('submit'));
 echo $this->form()->closeTag();

