<?php
 // module/Album/view/share/users/add.phtml:

 $title = 'Neues Mitglied hinzufuegen';
 $this->headTitle($title);
 ?>
 <h2><?php echo $this->escapeHtml($title); ?></h2>
 <br/><br/>
 <?php


 $form->setAttribute('action', $this->url('users', array('action' => 'add')));
 $form->prepare();

 echo $this->form()->openTag($form);
 echo $this->formHidden($form->get('id'));
 echo $this->formRow($form->get('first_name'));
 echo $this->formRow($form->get('last_name'));
 echo $this->formRow($form->get('gender'));
 echo $this->formRow($form->get('email'));
 echo $this->formRow($form->get('username'));
 echo $this->formRow($form->get('password'));
 echo $this->formRow($form->get('admin'));
 echo $this->formSubmit($form->get('submit'));
 echo $this->form()->closeTag();