 <?php
 // module/Share/view/share/users/delete.phtml:

 $title = 'Mitglied loeschen';
 $this->headTitle($title);
 ?>
 <h2><?php echo $this->escapeHtml($title); ?></h2>

 <p>Sind Sie sicher dass Sie 
     '<?php echo $this->escapeHtml($user->getFirstName())." ".$this->escapeHtml($user->getLastName());?>' 
    loeschen wollen?
 </p>
 <?php
 $url = $this->url('users', array(
     'action' => 'delete',
     'id'     => $this->id,
 ));
 ?>
 <form action="<?php echo $url; ?>" method="post">
 <div>
     <input type="hidden" name="id" value="<?php echo (int) $user->getId(); ?>" />
     <input type="submit" name="del" value="Ja" />
     <input type="submit" name="del" value="Nein" />
 </div>
 </form>

