<?php
 // module/Share/view/share/users/edit.phtml:

 $title = 'Mitglieder bearbeiten';
 $this->headTitle($title);
 ?>
 <h2><?php echo $this->escapeHtml($title); ?></h2>
<br/><br/>
 <?php
 $form = $this->form;
 $form->setAttribute('action', $this->url(
     'users',
     array(
         'action' => 'edit',
         'id'     => $this->id,
     )
 ));
 $form->prepare();

 
 echo $this->form()->openTag($form);

  echo $this->formHidden($form->get('id'));
 echo $this->formRow($form->get('first_name'));
 echo $this->formRow($form->get('last_name'));
  echo $this->formRow($form->get('gender'));
 echo $this->formSubmit($form->get('submit'));
 echo $this->form()->closeTag();
