<?php
 // module/Share/view/share/users/index.phtml:
 $title = 'Share Mitglieder';
 $this->headTitle($title);
 echo getenv('APP_ENV');
 ?>
 <h2><?php echo $this->escapeHtml($title); ?></h2>
 <p>
     <a href="<?php echo $this->url('users', array('action'=>'add'));?>">Neues Mitglied hinzuf&uuml;gen</a>
 </p>
 

 <br/> <br/>
 <table class="table">
 <tr>
     
	 <th>Vorname</th>
     <th>Nachname</th>
	 <th>Geschlecht</th>
	 <th>E-Mail</th>
	 <th>Username</th>
	 <th>Admin</th>
	 <th>MyFriend</th>
     <th>&nbsp;</th>
 </tr>
 <?php foreach ($users as $user) : ?>
 <tr>
     
	 <td><?php echo $this->escapeHtml($user->getFirstName());?></td>
     <td><?php echo $this->escapeHtml($user->getLastName());?></td>
	  <td><?php echo $this->escapeHtml($user->getGender());?></td>
	  <td><?php echo $this->escapeHtml($user->getEmail());?></td>
	  <td><?php echo $this->escapeHtml($user->getUserName());?></td>
	  <td><?php echo $this->escapeHtml($user->getAdmin());?></td>
	  <td>
	  <?php 
	  /*
	  find the pair
	  $tu = $objectManager->getRepository('Share\Entity\User')
                 ->findOneBy(array('users_trusted' => $user,));
	  
	  echo $tu->getFirstName();
	  */
	  foreach ($user->getUsersTrusted() as $trusted_user) { 
	    echo $trusted_user->getFirstName();
		 ?><br/>
		 <?php 
	  }
	  ?>
	  </td>
	  
     <td>
         <?php if ($user->getId() == $me->getId()) { ?>
		 <a href="<?php echo $this->url('users',
             array('action'=>'edit', 'id' => $user->getId()));?>">Bearbeiten</a>
         <a href="<?php echo $this->url('users',
             array('action'=>'delete', 'id' => $user->getId()));?>">L&ouml;schen</a>
		<?php } else { ?>
			 <a href="<?php echo $this->url('users',	
             array('action'=>'trust', 'id' => $user->getId()));?>">als Freund hinzuf&uuml;gen</a>
         <?php } ?>
     </td>
 </tr>
 <?php endforeach; ?>
 </table>
