<?php
 // module/Share/view/share/users/index.phtml:
 $title = 'Share Mitglieder';
 $this->headTitle($title);
 echo getenv('APP_ENV');
 ?>
 <h2><?php echo $this->escapeHtml($title); ?></h2>
 <p>
     <a href="<?php echo $this->url('users', array('action'=>'add'));?>">Neues Mitglied hinzuf&uuml;gen</a>
 </p>
 


 <br/> <br/>
 <table class="table">
 <tr>
     <th>Vorname</th>
     <th>Nachname</th>
	 <th>Geschlecht</th>
     <th>&nbsp;</th>
 </tr>
 <?php foreach ($users as $users) : ?>
 <tr>
     <td><?php echo $this->escapeHtml($users->getFirstName());?></td>
     <td><?php echo $this->escapeHtml($users->getLastName());?></td>
	  <td><?php echo $this->escapeHtml($users->getGender());?></td>
     <td>
         <a href="<?php echo $this->url('users',
             array('action'=>'edit', 'id' => $users->getId()));?>">Bearbeiten</a>
         <a href="<?php echo $this->url('users',
             array('action'=>'delete', 'id' => $users->getId()));?>">L&ouml;schen</a>
     </td>
 </tr>
 <?php endforeach; ?>
 </table>
