<?php
 // module/Album/view/share/products/add.phtml:

 $title = 'Neues Produkt hinzufuegen';
 $this->headTitle($title);
 ?>
 <h2><?php echo $this->escapeHtml($title); ?></h2>
 <br/><br/>
 <?php


 $form->setAttribute('action', $this->url('products', array('action' => 'add')));
 $form->prepare();

 echo $this->form()->openTag($form);
 echo $this->formHidden($form->get('id'));
 echo $this->formRow($form->get('owner_id'));
 echo $this->formRow($form->get('title'));
 echo $this->formRow($form->get('description'));
 echo $this->formRow($form->get('picture'));
 echo $this->formSubmit($form->get('submit'));
 echo $this->form()->closeTag();