<?php
 // module/Share/view/share/products/edit.phtml:

 $title = 'Produkt bearbeiten';
 $this->headTitle($title);
 ?>
 <h2><?php echo $this->escapeHtml($title); ?></h2>
<br/><br/>
 <?php
 $form = $this->form;
 $form->setAttribute('action', $this->url(
     'products',
     array(
         'action' => 'edit',
         'id'     => $this->id,
     )
 ));
 $form->prepare();

 echo $this->form()->openTag($form);
 echo $this->formHidden($form->get('id'));
 echo $this->formRow($form->get('title'));
 echo $this->formRow($form->get('description'));
 echo $this->formRow($form->get('owner'));
 echo $this->formRow($form->get('picture'));
 echo $this->formSubmit($form->get('submit'));
 echo $this->form()->closeTag();
