<?php
 // module/Share/view/share/products/index.phtml:
 $title = 'Share Produkte';
 $this->headTitle($title);
 echo getenv('APP_ENV');
 ?>
 <h2><?php echo $this->escapeHtml($title); ?></h2>
 <p>
     <a href="<?php echo $this->url('products', array('action'=>'add'));?>">Neues Produkt hinzuf&uuml;gen</a>
 </p>
 
 <br/> <br/>
 <table class="table">
 <tr>
     <th>Bezeichnung</th>
     <th>Details</th>
<!--	 <th>Besitzer</th> -->
	 <th>Bild</th>
     <th>&nbsp;</th>
 </tr>
 <?php foreach ($products as $products) : ?>
 <tr>
     <td><?php echo $this->escapeHtml($products->getTitle());?></td>
     <td><?php echo $this->escapeHtml($products->getDescription());?></td>
	 
	 <td><?php echo $this->escapeHtml($products->getPicture());?></td>
	 
     <td>
         <a href="<?php echo $this->url('products',
             array('action'=>'edit', 'id' => $products->getId()));?>">Bearbeiten</a>
         <a href="<?php echo $this->url('products',
             array('action'=>'delete', 'id' => $products->getId()));?>">L&ouml;schen</a>
     </td>
 </tr>
 <?php endforeach; ?>
 </table>
