<?php

 $title = 'Die Produkte zum ausleihen';
 $this->headTitle($title);
 ?>
 <h2><?php echo $this->escapeHtml($title); ?></h2>

		<table class="table"><tr>
		<?php
       foreach ($users_that_trust_me as $user) 
	   {
			
           echo '<td>Produkte von '.$user->getFirstName() .':</td><td></td><td></td></tr>';
		   foreach ($user->getProductUsers() as $product) 
		   {
		      echo '<td></td><td>'.$product->getTitle().'</td>';
			  ?>
			  <td>
			  <a href="<?php echo '../lend/add/'.$product->getId();?>">ausleihen</a>
			  
			  
			  </td></tr>
			 <?php

		   }
        }
		       
		?>
		<table>		
 
 <br/> <br/>
 